backend:
  name: git-gateway
  branch: main

media_folder: "archive"
public_folder: "archive"

collections:
  - name: "data"
    label: "Archive Data"
    files: # This must be plural
      - label: "Document List"
        name: "library"
        file: "data.json" # The path to your file
        fields:
          - label: "Documents"
            name: "documents"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Category", name: "cat", widget: "select", options: ["Exhibits", "Panels", "Admin"] }
              - { label: "Summary", name: "summary", widget: "text" }
              - { label: "PDF File", name: "file", widget: "file" }